// <auto-generated />
using System;
using Bital.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bital.Infrastructure.Migrations
{
    [DbContext(typeof(BitalNegocioDbContext))]
    [Migration("20260728130000_AddPermisosCatalogoDietas")]
    partial class AddPermisosCatalogoDietas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bital")
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.CategoriaEdad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EdadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<decimal>("FactorPorcion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriasEdad", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.DietaCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activa")
                        .HasDatabaseName("IX_DietaCatalogo_Activa");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_DietaCatalogo_Codigo");

                    b.HasIndex("FechaInicio", "FechaFin")
                        .HasDatabaseName("IX_DietaCatalogo_Vigencia");

                    b.ToTable("DietasCatalogo", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EtiquetaEnfermera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DevueltaEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntregadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntregadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoDietaDevolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoLogistica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FilaDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FotoDevolucionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneradaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneradaPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImpresaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoDevolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesDevolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrdenCocinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PreEntregadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecibidoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilaDietaId");

                    b.HasIndex("OrdenCocinaId");

                    b.ToTable("EtiquetasEnfermeria", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EventoAuditoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosAntes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DatosDespues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DuracionMs")
                        .HasColumnType("int");

                    b.Property<Guid?>("EntidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MensajeError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoEntidad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EventosAuditoria", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EventoTrazabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FilaDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilaDietaId")
                        .HasDatabaseName("IX_EventoTrazabilidad_FilaDietaId");

                    b.HasIndex("FechaEvento", "TipoEvento")
                        .HasDatabaseName("IX_EventoTrazabilidad_FechaTipo");

                    b.ToTable("EventosTrazabilidad", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaConciliacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFacturada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consistencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diferencia")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EtiquetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FilaDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Habitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pabellon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PacienteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResueltaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResueltoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDieta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("FilaDietaId");

                    b.ToTable("FilasConciliacion", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaDieta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aislado")
                        .HasColumnType("bit");

                    b.Property<string>("Aislamiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Alergico")
                        .HasColumnType("bit");

                    b.Property<bool>("CancelacionTardia")
                        .HasColumnType("bit");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<string>("Consistencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescripcionDieta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Habitacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdIngreso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObservacionAislamiento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("OrdenCocinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pabellon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Paciente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PacienteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SolicitadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SolicitadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TipoDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdIngreso")
                        .HasDatabaseName("IX_FilaDieta_IdIngreso");

                    b.HasIndex("OrdenCocinaId")
                        .HasDatabaseName("IX_FilaDieta_OrdenCocinaId");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("IX_FilaDieta_PacienteId");

                    b.HasIndex("TipoDietaId");

                    b.HasIndex("FechaOperativa", "Comida", "Estado")
                        .HasDatabaseName("IX_FilaDieta_FechaComidaEstado");

                    b.ToTable("FilasDietas", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.OrdenCocina", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChecklistJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneradoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneradoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TotalDietas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_OrdenCocina_Estado");

                    b.HasIndex("NumeroOrden")
                        .IsUnique()
                        .HasDatabaseName("IX_OrdenCocina_Numero");

                    b.HasIndex("FechaOperativa", "Comida")
                        .HasDatabaseName("IX_OrdenCocina_FechaComida");

                    b.ToTable("OrdenesCocina", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.ParametrosOperativos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModoCarga")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ParametrosOperativos", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.PermisoRol", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Permitido")
                        .HasColumnType("bit");

                    b.Property<Guid>("RolModuloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Ruta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolModuloId");

                    b.ToTable("PermisosRol", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.RolModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsSistema")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("RolesModulo", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.TarifaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DietaCatalogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VigenciaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VigenciaHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("VigenciaDesde", "VigenciaHasta")
                        .HasDatabaseName("IX_TarifaHistorico_Vigencia");

                    b.HasIndex("DietaCatalogoId", "Anio", "Activa")
                        .HasDatabaseName("IX_TarifaHistorico_DietaAnioActiva");

                    b.ToTable("TarifasHistorico", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.TiempoComidaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraEntrega")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraPreparacion")
                        .HasColumnType("time");

                    b.Property<int>("MinutosAlertaCierre")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiemposComida", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.UsuarioModulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identificacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RolModuloId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RolModuloId");

                    b.ToTable("UsuariosModulo", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.CapturaEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<string>("Consecutivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CuestionarioEncuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAnulacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaUltimaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotivoAnulacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("Nps")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroAtencion")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Pabellon")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiereSeguimiento")
                        .HasColumnType("bit");

                    b.Property<int?>("Sat")
                        .HasColumnType("int");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UsuarioAnulacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioFinaliza")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Consecutivo")
                        .IsUnique()
                        .HasDatabaseName("IX_CapturaEncuesta_Consecutivo");

                    b.HasIndex("CuestionarioEncuestaId");

                    b.HasIndex("NumeroDocumento", "Estado")
                        .HasDatabaseName("IX_CapturaEncuesta_DocumentoEstado");

                    b.ToTable("CapturasEncuesta", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.ConfiguracionEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Clave")
                        .IsUnique()
                        .HasDatabaseName("IX_ConfiguracionEncuesta_Clave");

                    b.ToTable("ConfiguracionesEncuesta", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.CuestionarioEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Canal", "Estado")
                        .HasDatabaseName("IX_Cuestionario_CanalEstado");

                    b.ToTable("Cuestionarios", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.IdentificacionPaciente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApellidosPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Canal")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaIdentificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombresPaciente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumeroAtencion")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pabellon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServicioAtencion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioIdentificador")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("IdentificacionesPacientes", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.IntentoLlamadaEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapturaEncuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaIntento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UsuarioRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CapturaEncuestaId", "FechaIntento")
                        .HasDatabaseName("IX_IntentoLlamadaEncuesta_CapturaFecha");

                    b.ToTable("IntentosLlamadaEncuesta", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.LogicaPreguntaCuestionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Operador")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PreguntaCuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PreguntaOrigenId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Valor")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaCuestionarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_LogicaPreguntaCuestionario_Pregunta");

                    b.ToTable("LogicasPreguntaCuestionario", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.OpcionPreguntaCuestionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("PreguntaCuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Valor")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PreguntaCuestionarioId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("IX_OpcionPreguntaCuestionario_PreguntaOrden");

                    b.ToTable("OpcionesPreguntaCuestionario", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.PreguntaCuestionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsRequerida")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<Guid>("SeccionCuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("SeccionCuestionarioId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("IX_PreguntaCuestionario_SeccionOrden");

                    b.ToTable("PreguntasCuestionario", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.ReglaCondicionalEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Campo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("EsPredeterminada")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Operador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Estado", "Campo")
                        .HasDatabaseName("IX_ReglaCondicionalEncuesta_EstadoCampo");

                    b.ToTable("ReglasCondicionalesEncuesta", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.RespuestaCapturaEncuesta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapturaEncuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaRespuesta")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OpcionPreguntaCuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PreguntaCuestionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ValorMultiple")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ValorTexto")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("OpcionPreguntaCuestionarioId");

                    b.HasIndex("PreguntaCuestionarioId");

                    b.HasIndex("CapturaEncuestaId", "PreguntaCuestionarioId")
                        .IsUnique()
                        .HasDatabaseName("IX_RespuestaCapturaEncuesta_CapturaPregunta");

                    b.ToTable("RespuestasCapturaEncuesta", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.SeccionCuestionario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CuestionarioEncuestaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CuestionarioEncuestaId", "Orden")
                        .IsUnique()
                        .HasDatabaseName("IX_SeccionCuestionario_CuestionarioOrden");

                    b.ToTable("SeccionesCuestionario", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EtiquetaEnfermera", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.FilaDieta", "FilaDieta")
                        .WithMany()
                        .HasForeignKey("FilaDietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bital.Domain.Entities.DietasCocina.OrdenCocina", "OrdenCocina")
                        .WithMany()
                        .HasForeignKey("OrdenCocinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilaDieta");

                    b.Navigation("OrdenCocina");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EventoTrazabilidad", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.FilaDieta", "FilaDieta")
                        .WithMany()
                        .HasForeignKey("FilaDietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilaDieta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaConciliacion", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.EtiquetaEnfermera", "Etiqueta")
                        .WithMany()
                        .HasForeignKey("EtiquetaId");

                    b.HasOne("Bital.Domain.Entities.DietasCocina.FilaDieta", "FilaDieta")
                        .WithMany()
                        .HasForeignKey("FilaDietaId");

                    b.Navigation("Etiqueta");

                    b.Navigation("FilaDieta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaDieta", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.OrdenCocina", null)
                        .WithMany("Dietas")
                        .HasForeignKey("OrdenCocinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bital.Domain.Entities.DietasCocina.DietaCatalogo", "TipoDieta")
                        .WithMany("Dietas")
                        .HasForeignKey("TipoDietaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TipoDieta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.TarifaHistorico", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.DietaCatalogo", "DietaCatalogo")
                        .WithMany("HistoricoTarifas")
                        .HasForeignKey("DietaCatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaCatalogo");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.CapturaEncuesta", b =>
                {
                    b.HasOne("Bital.Domain.Entities.Encuestas.CuestionarioEncuesta", "Cuestionario")
                        .WithMany()
                        .HasForeignKey("CuestionarioEncuestaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuestionario");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.IntentoLlamadaEncuesta", b =>
                {
                    b.HasOne("Bital.Domain.Entities.Encuestas.CapturaEncuesta", "CapturaEncuesta")
                        .WithMany("IntentosLlamada")
                        .HasForeignKey("CapturaEncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CapturaEncuesta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.LogicaPreguntaCuestionario", b =>
                {
                    b.HasOne("Bital.Domain.Entities.Encuestas.PreguntaCuestionario", "Pregunta")
                        .WithOne("Logica")
                        .HasForeignKey("Bital.Domain.Entities.Encuestas.LogicaPreguntaCuestionario", "PreguntaCuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.OpcionPreguntaCuestionario", b =>
                {
                    b.HasOne("Bital.Domain.Entities.Encuestas.PreguntaCuestionario", "Pregunta")
                        .WithMany("Opciones")
                        .HasForeignKey("PreguntaCuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.PreguntaCuestionario", b =>
                {
                    b.HasOne("Bital.Domain.Entities.Encuestas.SeccionCuestionario", "Seccion")
                        .WithMany("Preguntas")
                        .HasForeignKey("SeccionCuestionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seccion");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.RespuestaCapturaEncuesta", b =>
                {
                    b.HasOne("Bital.Domain.Entities.Encuestas.CapturaEncuesta", "CapturaEncuesta")
                        .WithMany("Respuestas")
                        .HasForeignKey("CapturaEncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bital.Domain.Entities.Encuestas.OpcionPreguntaCuestionario", "Opcion")
                        .WithMany()
                        .HasForeignKey("OpcionPreguntaCuestionarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bital.Domain.Entities.Encuestas.PreguntaCuestionario", "Pregunta")
                        .WithMany()
                        .HasForeignKey("PreguntaCuestionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CapturaEncuesta");

                    b.Navigation("Opcion");

                    b.Navigation("Pregunta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.SeccionCuestionario", b =>
                {
                    b.HasOne("Bital.Domain.Entities.Encuestas.CuestionarioEncuesta", "Cuestionario")
                        .WithMany("Secciones")
                        .HasForeignKey("CuestionarioEncuestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuestionario");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.DietaCatalogo", b =>
                {
                    b.Navigation("Dietas");

                    b.Navigation("HistoricoTarifas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.OrdenCocina", b =>
                {
                    b.Navigation("Dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.CapturaEncuesta", b =>
                {
                    b.Navigation("IntentosLlamada");

                    b.Navigation("Respuestas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.CuestionarioEncuesta", b =>
                {
                    b.Navigation("Secciones");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.PreguntaCuestionario", b =>
                {
                    b.Navigation("Logica");

                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("Bital.Domain.Entities.Encuestas.SeccionCuestionario", b =>
                {
                    b.Navigation("Preguntas");
                });
#pragma warning restore 612, 618
        }
    }
}

