// <auto-generated />
using System;
using Bital.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bital.Infrastructure.Migrations
{
    [DbContext(typeof(BitalNegocioDbContext))]
    [Migration("20260725235453_AddParametrosOperativos")]
    partial class AddParametrosOperativos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("bital")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.CategoriaEdad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EdadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<decimal>("FactorPorcion")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CategoriasEdad", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.DietaCatalogo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Activa")
                        .HasDatabaseName("IX_DietaCatalogo_Activa");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("IX_DietaCatalogo_Codigo");

                    b.HasIndex("FechaInicio", "FechaFin")
                        .HasDatabaseName("IX_DietaCatalogo_Vigencia");

                    b.ToTable("DietasCatalogo", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EtiquetaEnfermera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DevueltaEn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EntregadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntregadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoDietaDevolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoLogistica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FilaDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FotoDevolucionUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneradaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneradaPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImpresaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoDevolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObservacionesDevolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrdenCocinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PreEntregadaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecibidoPor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilaDietaId");

                    b.HasIndex("OrdenCocinaId");

                    b.ToTable("EtiquetasEnfermeria", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EventoTrazabilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DatosAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvento")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FilaDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FilaDietaId")
                        .HasDatabaseName("IX_EventoTrazabilidad_FilaDietaId");

                    b.HasIndex("FechaEvento", "TipoEvento")
                        .HasDatabaseName("IX_EventoTrazabilidad_FechaTipo");

                    b.ToTable("EventosTrazabilidad", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaConciliacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CantidadEntregada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadFacturada")
                        .HasColumnType("int");

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Consistencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Diferencia")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("EtiquetaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FilaDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Habitacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pabellon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PacienteId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResueltaEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResueltoPor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDieta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetaId");

                    b.HasIndex("FilaDietaId");

                    b.ToTable("FilasConciliacion", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaDieta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Aislado")
                        .HasColumnType("bit");

                    b.Property<string>("Aislamiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Alergias")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Alergico")
                        .HasColumnType("bit");

                    b.Property<bool>("CancelacionTardia")
                        .HasColumnType("bit");

                    b.Property<string>("Cedula")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<string>("Consistencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DescripcionDieta")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<string>("Habitacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IdIngreso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ObservacionAislamiento")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid?>("OrdenCocinaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pabellon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Paciente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PacienteId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Servicio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("SolicitadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("SolicitadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("TipoDietaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoDocumento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("IdIngreso")
                        .HasDatabaseName("IX_FilaDieta_IdIngreso");

                    b.HasIndex("OrdenCocinaId")
                        .HasDatabaseName("IX_FilaDieta_OrdenCocinaId");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("IX_FilaDieta_PacienteId");

                    b.HasIndex("TipoDietaId");

                    b.HasIndex("FechaOperativa", "Comida", "Estado")
                        .HasDatabaseName("IX_FilaDieta_FechaComidaEstado");

                    b.ToTable("FilasDietas", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.OrdenCocina", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaOperativa")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GeneradoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("GeneradoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroOrden")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TotalDietas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Estado")
                        .HasDatabaseName("IX_OrdenCocina_Estado");

                    b.HasIndex("NumeroOrden")
                        .IsUnique()
                        .HasDatabaseName("IX_OrdenCocina_Numero");

                    b.HasIndex("FechaOperativa", "Comida")
                        .HasDatabaseName("IX_OrdenCocina_FechaComida");

                    b.ToTable("OrdenesCocina", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.TarifaHistorico", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("DietaCatalogoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("VigenciaDesde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VigenciaHasta")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("VigenciaDesde", "VigenciaHasta")
                        .HasDatabaseName("IX_TarifaHistorico_Vigencia");

                    b.HasIndex("DietaCatalogoId", "Anio", "Activa")
                        .HasDatabaseName("IX_TarifaHistorico_DietaAnioActiva");

                    b.ToTable("TarifasHistorico", "dietas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.TiempoComidaConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Comida")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("HoraCierre")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraEntrega")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraPreparacion")
                        .HasColumnType("time");

                    b.Property<int>("MinutosAlertaCierre")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModificadoEn")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModificadoPor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TiemposComida", "bital");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EtiquetaEnfermera", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.FilaDieta", "FilaDieta")
                        .WithMany()
                        .HasForeignKey("FilaDietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bital.Domain.Entities.DietasCocina.OrdenCocina", "OrdenCocina")
                        .WithMany()
                        .HasForeignKey("OrdenCocinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilaDieta");

                    b.Navigation("OrdenCocina");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.EventoTrazabilidad", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.FilaDieta", "FilaDieta")
                        .WithMany()
                        .HasForeignKey("FilaDietaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilaDieta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaConciliacion", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.EtiquetaEnfermera", "Etiqueta")
                        .WithMany()
                        .HasForeignKey("EtiquetaId");

                    b.HasOne("Bital.Domain.Entities.DietasCocina.FilaDieta", "FilaDieta")
                        .WithMany()
                        .HasForeignKey("FilaDietaId");

                    b.Navigation("Etiqueta");

                    b.Navigation("FilaDieta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.FilaDieta", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.OrdenCocina", null)
                        .WithMany("Dietas")
                        .HasForeignKey("OrdenCocinaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Bital.Domain.Entities.DietasCocina.DietaCatalogo", "TipoDieta")
                        .WithMany("Dietas")
                        .HasForeignKey("TipoDietaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TipoDieta");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.TarifaHistorico", b =>
                {
                    b.HasOne("Bital.Domain.Entities.DietasCocina.DietaCatalogo", "DietaCatalogo")
                        .WithMany("HistoricoTarifas")
                        .HasForeignKey("DietaCatalogoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DietaCatalogo");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.DietaCatalogo", b =>
                {
                    b.Navigation("Dietas");

                    b.Navigation("HistoricoTarifas");
                });

            modelBuilder.Entity("Bital.Domain.Entities.DietasCocina.OrdenCocina", b =>
                {
                    b.Navigation("Dietas");
                });
#pragma warning restore 612, 618
        }
    }
}
